### ISSUE TITLE
error on compile

### ISSUE THREAD

**Issue by johnjohnsp1** [vletoux/PingCastleCloud#1]
Hi Vincent,
using VStudio2019 to compile but getting this error:

Error | CS1566 | Error reading resource 'PingCastleCloud.Template.bootstrap-table.min.css.gz' -- 'Could not find file 'C:\temp\PingCastleCloud\Template\bootstrap-table.min.css.gz'.'

used git clone --recurse to download the source, i do something wrong ?

thanks

**Comment by PrudhommeWTF** [comment]
Hi,

In fact all the Bootstrap suit is missing from Template folder, generating error at build.

**Comment by PrudhommeWTF** [comment]
After further tests, I just found quick workarrounds:
- create GZ file for https://www.cdnpkg.com/bootstrap-table/file/bootstrap-table.min.css/?id=24791 and https://www.cdnpkg.com/bootstrap-table/file/bootstrap-table.min.js/?id=24791 in Template
- copy bootstrap files from PingCastle repo under template folder into Template
Try build again :-)

**Comment by vletoux** [comment]
i added the missing files - it should be ok
