### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by tobi-coder** [vletoux/PingCastleCloud#2]
Hi

This is not really an issue. Is PingCastelCloud still under development? Is there a way to get an already compiled version?

Best regards
Tobi

**Comment by vletoux** [comment]
This has been merged with the official PingCastle program.
Compiled releases can be found there.
This repository will no longer been updated

**Comment by ruppde** [comment]
I was wondering the same. consider archiving the repo, then it's clear for everybody:
https://docs.github.com/en/repositories/archiving-a-github-repository/archiving-repositories
